gnn_saving_path: 'checkpoints'
gnn_name: 'gcn'

param:
  ba_2motifs:
    learning_rate: 0.005
    weight_decay: 0.0
    milestones: None
    gamma: None
    batch_size: 32
    num_epochs: 800
    num_early_stop: 200
    gnn_latent_dim:
      - 20
      - 20
      - 20
    gnn_dropout: 0.0
    add_self_loop: True
    gcn_adj_normalization: False
    gnn_emb_normalization: False
    graph_classification: True
    node_classification: False
    gnn_nonlinear: 'relu'
    readout: 'mean'
    fc_latent_dim: []
    fc_dropout: 0.0
    fc_nonlinear: 'relu'
  bace:
    learning_rate: 0.01
    weight_decay: 0.0
    milestones: None
    gamma: None
    batch_size: 64
    num_epochs: 400
    num_early_stop: 0
    gnn_latent_dim:
      - 128
      - 128
      - 128
    gnn_dropout: 0.0
    add_self_loop: True
    gcn_adj_normalization: True
    gnn_emb_normalization: False
    graph_classification: True
    node_classification: False
    gnn_nonlinear: 'relu'
    readout: 'max'
    fc_latent_dim: [ ]
    fc_dropout: 0.0
    fc_nonlinear: 'relu'    
  bbbp:
    learning_rate: 0.005
    weight_decay: 0
    milestones: None
    gamma: None
    batch_size: 64
    num_epochs: 800
    num_early_stop: 200
    gnn_latent_dim:
      - 128
      - 128
      - 128
    gnn_dropout: 0
    add_self_loop: True
    gcn_adj_normalization: True
    gnn_emb_normalization: False
    graph_classification: True
    node_classification: False
    gnn_nonlinear: 'relu'
    readout: 'max'
    fc_latent_dim: []
    fc_dropout: 0.0
    fc_nonlinear: 'relu'
  graph_sst2:
    learning_rate: 0.001
    weight_decay: 0.0
    milestones: None
    gamma: None
    batch_size: 128
    num_epochs: 50
    num_early_stop: 0
    gnn_latent_dim:
      - 128
      - 128
      - 128
    gnn_dropout: 0.0
    add_self_loop: True
    gcn_adj_normalization: True
    gnn_emb_normalization: False
    graph_classification: True
    node_classification: False
    gnn_nonlinear: 'relu'
    readout: 'max'
    fc_latent_dim: []
    fc_dropout: 0.0
    fc_nonlinear: 'relu'
  mutag:
    learning_rate: 0.005
    weight_decay: 0
    milestones: None
    gamma: None
    batch_size: 32
    num_epochs: 1000
    num_early_stop: 100
    gnn_latent_dim:
      - 128
      - 128
      - 128
    gnn_dropout: 0
    add_self_loop: True
    gcn_adj_normalization: True
    gnn_emb_normalization: False
    graph_classification: True
    node_classification: False
    gnn_nonlinear: 'relu'
    readout: 'mean'
    fc_latent_dim: []
    fc_dropout: 0.0
    fc_nonlinear: 'relu'
  twitter:
    learning_rate: 0.001
    weight_decay: 5e-4
    milestones: None
    gamma: None
    batch_size: 128
    num_epochs: 50
    num_early_stop: 0
    gnn_latent_dim:
      - 128
      - 128
      - 128
    gnn_dropout: 0.0
    add_self_loop: True
    gcn_adj_normalization: True
    gnn_emb_normalization: False
    graph_classification: True
    node_classification: False
    gnn_nonlinear: 'relu'
    readout: 'max'
    fc_latent_dim: []
    fc_dropout: 0.0
    fc_nonlinear: 'relu'
  ba_shapes:
    learning_rate: 0.005
    weight_decay: 5e-4
    milestones: None
    gamma: None
    batch_size: 1
    num_epochs: 800
    num_early_stop: 0
    gnn_latent_dim:
      - 20
      - 20
      - 20
    gnn_dropout: 0.0
    add_self_loop: True
    gcn_adj_normalization: False
    gnn_emb_normalization: True
    graph_classification: False
    node_classification: True
    gnn_nonlinear: 'relu'
    readout: 'identity'
    fc_latent_dim: []
    fc_dropout: 0.0
    fc_nonlinear: 'relu'
  ba_shapes_khop_graph:
    learning_rate: 0.005
    weight_decay: 5e-4
    milestones: None
    gamma: None
    batch_size: 1
    num_epochs: 800
    num_early_stop: 0
    gnn_latent_dim:
      - 20
      - 20
      - 20
    gnn_dropout: 0.0
    add_self_loop: True
    gcn_adj_normalization: False
    gnn_emb_normalization: True
    graph_classification: True
    node_classification: False
    gnn_nonlinear: 'relu'
    readout: 'mean'
    fc_latent_dim: []
    fc_dropout: 0.0
    fc_nonlinear: 'relu'
    
    
  ba_shapes_2hop_graph:
    learning_rate: 0.005
    weight_decay: 5e-4
    milestones: None
    gamma: None
    batch_size: 1
    num_epochs: 800
    num_early_stop: 0
    gnn_latent_dim:
      - 20
      - 20
      - 20
    gnn_dropout: 0.0
    add_self_loop: True
    gcn_adj_normalization: False
    gnn_emb_normalization: True
    graph_classification: True
    node_classification: False
    gnn_nonlinear: 'relu'
    readout: 'mean'
    fc_latent_dim: []
    fc_dropout: 0.0
    fc_nonlinear: 'relu'